version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000" # Map container's port 5000 to host's port 5000
    volumes:
      - ./Backend:/app # Optional: Mount the Backend folder for development purposes
    environment:
      - ASPNETCORE_ENVIRONMENT=Development