name: Build and Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [ Debug ]
        architecture: [ x64 ]
        os: [ linux, windows ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build WinUI3 project
        if: matrix.os == 'windows'
        run: dotnet build ./StockManagement-WinUI3.csproj --configuration ${{ matrix.configuration }} --runtime win-${{ matrix.architecture }} /p:EnableWindowsTargeting=true

      - name: Build ASP.NET project
        if: matrix.os == 'linux'
        run: dotnet build ./Backend/Backend.csproj --configuration ${{ matrix.configuration }} --runtime ${{ matrix.os }}-${{ matrix.architecture }}

      - name: Publish WinUI3 project
        if: matrix.os == 'windows'
        run: dotnet publish ./StockManagement-WinUI3.csproj --configuration ${{ matrix.configuration }} --runtime win-${{ matrix.architecture }} --output ./publish/StockManagement-WinUI3/${{ matrix.configuration }}/win-${{ matrix.architecture }} /p:EnableWindowsTargeting=true

      - name: Publish ASP.NET project
        if: matrix.os == 'linux'
        run: dotnet publish ./Backend/Backend.csproj --configuration ${{ matrix.configuration }} --runtime ${{ matrix.os }}-${{ matrix.architecture }} --output ./publish/Backend/${{ matrix.configuration }}/${{ matrix.os }}-${{ matrix.architecture }}
        
      - name: Upload WinUI3 build artifacts
        if: matrix.os == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: StockManagement-WinUI3
          path: ./publish/StockManagement-WinUI3/${{ matrix.configuration }}/win-${{ matrix.architecture }}

      - name: Upload ASP.NET build artifacts
        if: matrix.os == 'linux'
        uses: actions/upload-artifact@v4
        with:
          name: Backend
          path: ./publish/Backend/${{ matrix.configuration }}/linux-${{ matrix.architecture }}